In [1]:
import numpy as np
import pandas as pd
import sklearn
import scipy

In [2]:
df = pd.read_csv('shilmat_data.csv')
df

date        day  income
0   12/9/2022     monday     160
1   13/9/2022    tuesday     150
2   14/9/2022  wednesday       0
3   15/9/2022   thursday     250
4   16/9/2022     friday     290
5   17/9/2022   saturday     440
6   18/9/2022     sunday     350
7   19/9/2022     monday       0
8   20/9/2022    tuesday     700
9   21/8/2022  wednesday       0
10  22/9/2022   thursday     830
11  23/9/2022     friday     110
12  24/9/2022   saturday     390
13  25/9/2022     sunday     250
14  26/9/2022     monday     360
15  27/9/2022    tuesday     640
16  28/9/2022  wednesday     160
17  29/9/2022   thursday     260

In [3]:
df['day'].unique()

array(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday',
       'sunday'], dtype=object)

In [4]:
from sklearn.preprocessing import LabelEncoder

le_day= LabelEncoder()
df['day']= le_day.fit_transform(df['day'])

In [6]:
df['day'].unique()

array([1, 5, 6, 4, 0, 2, 3])

In [7]:
df

date  day  income
0   12/9/2022    1     160
1   13/9/2022    5     150
2   14/9/2022    6       0
3   15/9/2022    4     250
4   16/9/2022    0     290
5   17/9/2022    2     440
6   18/9/2022    3     350
7   19/9/2022    1       0
8   20/9/2022    5     700
9   21/8/2022    6       0
10  22/9/2022    4     830
11  23/9/2022    0     110
12  24/9/2022    2     390
13  25/9/2022    3     250
14  26/9/2022    1     360
15  27/9/2022    5     640
16  28/9/2022    6     160
17  29/9/2022    4     260

In [18]:
df=df.drop(columns=['date'])

In [20]:
X=df.drop('income',axis=1)
y=df['income']

In [68]:
y

day
0     1
1     5
2     6
3     4
4     0
5     2
6     3
7     1
8     5
9     6
10    4
11    0
12    2
13    3
14    1
15    5
16    6
17    4

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

day
8     5
12    2
4     0
7     1
16    6
13    3
2     6
0     1
10    4
1     5
17    4
5     2
15    5
14    1

 <!-- Using LinearRegression algorithm -->

In [24]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [25]:
model.predict(X_test)-y_test

11    172.352168
9     372.628121
6     -22.509855
3      92.536137
Name: income, dtype: float64

In [26]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
y_pred=model.predict(X_test)
error =np.sqrt(mean_squared_error(y_test,y_pred))
error

210.72886403191723

<!-- Using DecisionTreeRegressor algorithm -->

In [27]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()
model.fit(X_train,y_train)


DecisionTreeRegressor()

In [29]:
y_pred =model.predict(X_test)
error = np.sqrt(mean_squared_error(y_test,y_pred))
error

184.27221711370382

<!-- Using RandomForest algorithims -->

In [33]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(random_state=0)
model.fit(X_train,y_train)


RandomForestRegressor(random_state=0)

In [34]:
y_pred= model.predict(X_test)
error=np.sqrt(mean_squared_error(y_test,y_pred))
error

153.37703665113003

<!-- Finding the best  model  -->
        <!-- DescionTreeRegressor -->

In [41]:
from sklearn.model_selection import GridSearchCV
max_depth = [None,2,4,6,8,10,12]
params={'max_depth': max_depth}
regressor = DecisionTreeRegressor(random_state=0)
gs  = GridSearchCV(regressor,params,scoring='neg_mean_squared_error')
gs.fit(X_train,y_train)

GridSearchCV(estimator=DecisionTreeRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [42]:
best_reg_model =gs.best_estimator_
best_reg_model.fit(X_train,y_train)


DecisionTreeRegressor(max_depth=2, random_state=0)

In [43]:
y_pred = best_reg_model.predict(X_test)
error = np.sqrt(mean_squared_error(y_test,y_pred))
error

165.19382555047267

<!-- Finding the best  model  -->
        <!-- RandomForestRegressor -->

In [44]:
max_depth = [None,2,4,6,8,10,12]
params={'max_depth': max_depth}
regressor = RandomForestRegressor(random_state=0)
gs  = GridSearchCV(regressor,params,scoring='neg_mean_squared_error')
gs.fit(X_train,y_train)

GridSearchCV(estimator=RandomForestRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [45]:
best_reg_model =gs.best_estimator_
best_reg_model.fit(X_train,y_train)

RandomForestRegressor(max_depth=2, random_state=0)

In [47]:
y_pred = best_reg_model.predict(X_test)
error = np.sqrt(mean_squared_error(y_test,y_pred))
error

138.02826772187893

In [101]:
X_train

day
8     5
12    2
4     0
7     1
16    6
13    3
2     6
0     1
10    4
1     5
17    4
5     2
15    5
14    1

In [116]:
some_input = np.array([['friday']])
some_input

array([['friday']], dtype='<U6')

In [117]:
# some_input = np.array([['friday']])
some_input[:,0]= le_day.transform(some_input[:,0])
some_input=some_input.astype(float)
some_input


array([[0.]])

In [119]:
y_pred =best_reg_model.predict(some_input)
y_pred

c:\Users\25192\Documents\py\huletshi_shilmat\venv\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([245.91906205])

<!-- Save model -->

In [123]:
import pickle

data = {'model': best_reg_model , 'le_day': le_day}

with open('current_model_19_02_test.pkl','wb') as file:
    pickle.dump(data,file)

<!-- load model -->

In [ ]:
with open('current_model_19_02_test.pkl','wb') as file:
    data = pickle.load(file)
    
regeressor = data['model']
le_day = data['le_day']